### ISSUE TITLE
关于网页跳转

### ISSUE THREAD

**Issue by al1020119** [GTMYang/GTMRouter#1]
请问一下，关于网页跳转这么没有对应的方案，要怎么使用或者怎么处理？

**Comment by GTMYang** [comment]
@al1020119 定义你自己的网页容器控制器（UIViewController）,url作为参数传过去。跟普通视图一样的方式

**Comment by GTMYang** [comment]
@al1020119 新版本增加了网页跳转的支持

**Comment by GTMYang** [comment]
@al1020119  
v1.3.4
